### ISSUE TITLE
02_reconstruct couldn't run through on rtx 3070

### ISSUE THREAD

**Issue by jiayangshi** [ahendriksen/noise2inverse#2]
Hi, while running the code with provided environment setup, I find the [02_reconstruct.ipynb](https://github.com/ahendriksen/noise2inverse/blob/3841c471130c6b3638363f6dfbaedc214b848131/02_reconstruct.ipynb) couldn't run through.

It get stuck on [```fbp(A, sino) ```](https://github.com/ahendriksen/noise2inverse/blob/3841c471130c6b3638363f6dfbaedc214b848131/noise2inverse/tomo.py#L91), specifically on [```A.T(filtered)```](https://github.com/ahendriksen/noise2inverse/blob/3841c471130c6b3638363f6dfbaedc214b848131/noise2inverse/tomo.py#L97). So I guess it is the (cuda?) compatibility problem of tomosipo operator with the new GPU.  

Running environment is installed with the given yml file, the GPU model is rtx 3070. 

After some more tests, it does run through on rtx 2080Ti, but doesn't run through on rtx 3070 and rtx 3090. I have only access to these two types of 30 rtx graphic card.

**Comment by ahendriksen** [comment]
Hi, 

Are you using windows? Also you might want to try installing with cudatoolkit=11
when you are using a recent video card.

**Comment by jiayangshi** [comment]
Hi, 

No, they are on Linux, rtx 3070(Ubuntu 21.10) and rtx 3090(CentOS 7). Yes I have already tried to update the cudatoolkit version to above 11. And it indeed solves the [A.T(filtered)](https://github.com/ahendriksen/noise2inverse/blob/3841c471130c6b3638363f6dfbaedc214b848131/noise2inverse/tomo.py#L97) problem.

There is still some package conflicts. For new pytorch version (>=1.7) that compatible with cudatoolkit=11, the [torch.rfft](https://github.com/ahendriksen/noise2inverse/blob/3841c471130c6b3638363f6dfbaedc214b848131/noise2inverse/tomo.py#L68) is deprecated. And the new rfft() has a different function signature.

Anyway, the tomosipo operator problem solves with cudatoolkit=11 on new GPU. Thank you.

**Comment by ahendriksen** [comment]
Hi, yes with the speed of updates coming from PyTorch and Nvidia it is difficult to keep all my projects up to date. In practice, I have found that most people look at the repository mostly to check out specifics so they can incorporate Noise2Inverse in their own reconstruction pipelines.

Thanks for trying out and I am sorry that bit rot has set in so quickly.
